// <auto-generated />
using System;
using AV.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AV.Migrations
{
    [DbContext(typeof(AVContext))]
    [Migration("20240408142907_update_newTables3")]
    partial class update_newTables3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("AV.Models.Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Adressen");
                });

            modelBuilder.Entity("AV.Models.Auftrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdresseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProduktId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdresseId");

                    b.HasIndex("ProduktId");

                    b.ToTable("Auftraege");
                });

            modelBuilder.Entity("AV.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuftragId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProduktId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuftragId");

                    b.HasIndex("ProduktId");

                    b.ToTable("Positionen");
                });

            modelBuilder.Entity("AV.Models.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdresseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdresseId");

                    b.ToTable("Produkte");
                });

            modelBuilder.Entity("AV.Models.Auftrag", b =>
                {
                    b.HasOne("AV.Models.Adresse", "Adresse")
                        .WithMany("Auftrag")
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AV.Models.Produkt", "Produkt")
                        .WithMany()
                        .HasForeignKey("ProduktId");

                    b.Navigation("Adresse");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("AV.Models.Position", b =>
                {
                    b.HasOne("AV.Models.Auftrag", "Auftrag")
                        .WithMany()
                        .HasForeignKey("AuftragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AV.Models.Produkt", "Produkt")
                        .WithMany()
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auftrag");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("AV.Models.Produkt", b =>
                {
                    b.HasOne("AV.Models.Adresse", null)
                        .WithMany("Produkt")
                        .HasForeignKey("AdresseId");
                });

            modelBuilder.Entity("AV.Models.Adresse", b =>
                {
                    b.Navigation("Auftrag");

                    b.Navigation("Produkt");
                });
#pragma warning restore 612, 618
        }
    }
}
