// <auto-generated />
using System;
using AV.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AV.Migrations
{
    [DbContext(typeof(AVContext))]
    [Migration("20240402172158_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("AV.Models.Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Adressen");
                });

            modelBuilder.Entity("AV.Models.Auftrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdresseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdresseId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdresseId")
                        .IsUnique();

                    b.HasIndex("AdresseId1")
                        .IsUnique();

                    b.ToTable("Auftraege");
                });

            modelBuilder.Entity("AV.Models.Auftrag", b =>
                {
                    b.HasOne("AV.Models.Adresse", "Adresse")
                        .WithOne()
                        .HasForeignKey("AV.Models.Auftrag", "AdresseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AV.Models.Adresse", null)
                        .WithOne("Auftrag")
                        .HasForeignKey("AV.Models.Auftrag", "AdresseId1");

                    b.Navigation("Adresse");
                });

            modelBuilder.Entity("AV.Models.Adresse", b =>
                {
                    b.Navigation("Auftrag");
                });
#pragma warning restore 612, 618
        }
    }
}
